#' RAG knowledge base for AI perspectives (E7 / spec 009)
#'
#' @description
#' Retrieval-Augmented Generation primitives for the `nemeton` core:
#' ingest forestry documents into a vector store, embed queries, and
#' retrieve the most relevant passages so that the AI perspectives
#' generated by `nemetonshiny` can cite verifiable sources.
#'
#' The subsystem is **opt-in**: the knowledge tables are created by
#' [enable_rag()], not by the default [db_migrate()] sequence, because
#' the PostgreSQL backend needs the `pgvector` extension which is not
#' guaranteed on every deployment (ADR-012).
#'
#' Two storage backends are supported transparently, mirroring the
#' monitoring subsystem:
#'
#'   * **PostgreSQL + pgvector** -- `embedding` is a `vector(3072)` column
#'     and [retrieve_knowledge()] runs an exact cosine KNN via the `<=>`
#'     operator.
#'   * **SQLite** -- `embedding` is a JSON array in a `TEXT` column and the
#'     cosine similarity is computed in R. Fine for a single-project
#'     corpus (a few thousand chunks).
#'
#' Embeddings are produced by a configurable provider: Mistral (default,
#' ADR-004 souverainete FR), OpenAI, or Voyage AI (Anthropic ecosystem).
#' All three expose an OpenAI-compatible `/embeddings` endpoint.
#'
#' @name rag
NULL


# ---- Backend helpers -------------------------------------------------

.rag_is_pg <- function(con) inherits(con, "PqConnection")

.assert_rag_schema <- function(con) {
  if (!DBI::dbExistsTable(con, "knowledge_chunk") ||
      !DBI::dbExistsTable(con, "knowledge_document")) {
    cli::cli_abort(c(
      "RAG knowledge base schema not found.",
      "i" = "Run {.code enable_rag(con)} to create the knowledge tables."
    ))
  }
  invisible(TRUE)
}


#' Enable the RAG knowledge base schema (opt-in migration)
#'
#' Applies the bundled RAG migration (`knowledge_document` +
#' `knowledge_chunk`) on top of the base monitoring schema. This is a
#' separate, explicit step -- *not* part of [db_migrate()] -- because the
#' PostgreSQL variant requires the `pgvector` extension which existing
#' TimescaleDB deployments may not have installed.
#'
#' Idempotent: re-running is a no-op once the migration is recorded in
#' `schema_migration`.
#'
#' @param con A `DBIConnection` returned by [db_connect()].
#'
#' @return Invisible character vector of migration versions applied during
#'   this call (empty if already enabled).
#'
#' @seealso [ingest_knowledge_document()], [retrieve_knowledge()].
#' @export
enable_rag <- function(con) {
  if (!inherits(con, "DBIConnection")) {
    cli::cli_abort("{.arg con} must be a {.cls DBIConnection}.")
  }
  driver <- if (inherits(con, "SQLiteConnection")) "sqlite" else "pg"
  # Ensure the base schema (and schema_migration) exists first; idempotent.
  db_migrate(con)
  rag_dir <- system.file(file.path("db", "migrations", driver, "rag"),
                         package = "nemeton")
  if (!nzchar(rag_dir) || !dir.exists(rag_dir)) {
    cli::cli_abort("RAG migrations directory for driver {.val {driver}} not found.")
  }
  tryCatch(
    invisible(db_migrate(con, migrations_dir = rag_dir)),
    error = function(e) {
      msg <- conditionMessage(e)
      if (identical(driver, "pg") && grepl("vector|extension", msg, ignore.case = TRUE)) {
        cli::cli_abort(c(
          "Could not enable RAG: the {.pkg pgvector} extension is unavailable on this server.",
          "x" = msg,
          "i" = "Install pgvector server-side, or use a SQLite backend for local RAG."
        ))
      }
      stop(e)
    }
  )
}


# ---- Text chunking ---------------------------------------------------

# Rough token estimate: ~4 characters per token holds well for FR/EN
# under the Mistral/OpenAI tokenizers.
.estimate_tokens <- function(text) {
  as.integer(ceiling(nchar(text) / 4))
}

# Sliding-window chunker over whitespace-delimited words, sized by
# estimated tokens with a token overlap between consecutive chunks.
.chunk_text <- function(text, size = 512L, overlap = 50L) {
  size <- as.integer(size)
  overlap <- as.integer(overlap)
  if (is.na(size) || size < 1L) {
    cli::cli_abort("{.arg chunk_size} must be a positive integer.")
  }
  if (is.na(overlap) || overlap < 0L || overlap >= size) {
    cli::cli_abort("{.arg chunk_overlap} must be in [0, chunk_size).")
  }
  text <- paste(as.character(text), collapse = "\n")
  words <- unlist(strsplit(text, "[[:space:]]+"))
  words <- words[nzchar(words)]
  n <- length(words)
  if (!n) return(character(0))
  wtok <- pmax(1L, as.integer(ceiling(nchar(words) / 4)))

  out <- character(0)
  i <- 1L
  while (i <= n) {
    cum <- 0L
    j <- i
    while (j <= n && cum + wtok[j] <= size) {
      cum <- cum + wtok[j]
      j <- j + 1L
    }
    if (j == i) j <- i + 1L                       # a single oversized word
    out <- c(out, paste(words[i:(j - 1L)], collapse = " "))
    if (j > n) break
    # Step the window start back by ~overlap tokens.
    back <- 0L
    k <- j - 1L
    while (k > i && back + wtok[k] <= overlap) {
      back <- back + wtok[k]
      k <- k - 1L
    }
    i <- max(i + 1L, k + 1L)                       # guarantee forward progress
  }
  out
}


# ---- Embedding providers ---------------------------------------------

.provider_default_model <- function(provider) {
  switch(provider,
    mistral = "mistral-embed",
    openai  = "text-embedding-3-large",
    voyage  = "voyage-3-large"
  )
}

.resolve_embed_key <- function(provider, api_key) {
  if (!is.null(api_key) && nzchar(api_key)) return(api_key)
  primary <- switch(provider,
    mistral = "NEMETON_MISTRAL_API_KEY",
    openai  = "NEMETON_OPENAI_API_KEY",
    voyage  = "NEMETON_VOYAGE_API_KEY"
  )
  fallback <- switch(provider,
    mistral = "MISTRAL_API_KEY",
    openai  = "OPENAI_API_KEY",
    voyage  = "VOYAGE_API_KEY"
  )
  key <- Sys.getenv(primary, "")
  if (!nzchar(key)) key <- Sys.getenv(fallback, "")
  if (!nzchar(key)) {
    url <- switch(provider,
      mistral = "https://console.mistral.ai/api-keys/",
      openai  = "https://platform.openai.com/api-keys",
      voyage  = "https://dash.voyageai.com/"
    )
    cli::cli_abort(c(
      "No API key for embedding provider {.val {provider}}.",
      "i" = "Set {.envvar {primary}} (or {.envvar {fallback}}), or pass {.arg api_key}.",
      "i" = "Get one at {.url {url}}."
    ))
  }
  key
}

.assert_httr2 <- function() {
  if (!requireNamespace("httr2", quietly = TRUE)) {
    cli::cli_abort(c(
      "Package {.pkg httr2} required for embedding API calls.",
      "i" = "Install with {.code install.packages('httr2')}."
    ))
  }
}

.with_embed_retry <- function(req) {
  httr2::req_retry(
    req,
    max_tries    = 3L,
    is_transient = function(resp) httr2::resp_status(resp) %in% c(429, 500, 502, 503, 504),
    backoff      = function(i) min(30, 2^i)
  )
}

# Parse the OpenAI-compatible {data: [{embedding: [...]}]} body into a
# numeric matrix (n rows x d columns), preserving input order.
.embed_body_to_matrix <- function(data_list) {
  embs <- lapply(data_list, function(d) as.numeric(unlist(d$embedding)))
  do.call(rbind, embs)
}

.embed_endpoint_call <- function(url, api_key, body) {
  .assert_httr2()
  req <- httr2::request(url)
  req <- httr2::req_headers(req,
    Authorization  = paste("Bearer", api_key),
    `Content-Type` = "application/json"
  )
  req <- httr2::req_body_json(req, body)
  req <- httr2::req_timeout(req, 60L)
  req <- .with_embed_retry(req)
  resp <- httr2::req_perform(req)
  body <- httr2::resp_body_json(resp)
  .embed_body_to_matrix(body$data)
}

.mistral_embed <- function(texts, api_key) {
  .embed_endpoint_call(
    "https://api.mistral.ai/v1/embeddings",
    api_key,
    list(model = "mistral-embed", input = as.list(texts))
  )
}

.openai_embed <- function(texts, api_key) {
  .embed_endpoint_call(
    "https://api.openai.com/v1/embeddings",
    api_key,
    list(model = "text-embedding-3-large", input = as.list(texts))
  )
}

.voyage_embed <- function(texts, api_key) {
  .embed_endpoint_call(
    "https://api.voyageai.com/v1/embeddings",
    api_key,
    list(model = "voyage-3-large", input = as.list(texts))
  )
}

# Single entry point for embedding text (batched). Mocked in tests.
.embed_texts <- function(texts, provider = "mistral", api_key = NULL,
                         lang = NULL, batch_size = 32L) {
  provider <- match.arg(provider, c("mistral", "openai", "voyage"))
  texts <- as.character(texts)
  if (!length(texts)) {
    cli::cli_abort("No text to embed.")
  }
  key <- .resolve_embed_key(provider, api_key)
  groups <- split(seq_along(texts), ceiling(seq_along(texts) / batch_size))
  mats <- lapply(groups, function(ii) {
    switch(provider,
      mistral = .mistral_embed(texts[ii], key),
      openai  = .openai_embed(texts[ii], key),
      voyage  = .voyage_embed(texts[ii], key)
    )
  })
  do.call(rbind, mats)
}


# ---- Vector encoding -------------------------------------------------

# Pad with zeros / truncate a vector to exactly `target` dims. Zero
# padding is transparent for cosine similarity within a provider.
.fit_embedding_dim <- function(vec, target = 3072L) {
  vec <- as.numeric(vec)
  vec[!is.finite(vec)] <- 0
  n <- length(vec)
  if (n == target) return(vec)
  if (n > target)  return(vec[seq_len(target)])
  c(vec, rep(0, target - n))
}

.pg_vector_literal <- function(vec) {
  paste0("[", paste(vec, collapse = ","), "]")
}

.embedding_json <- function(vec) {
  as.character(jsonlite::toJSON(as.numeric(vec), digits = NA))
}

.decode_embedding <- function(x) {
  if (is.null(x) || length(x) != 1L || is.na(x) || !nzchar(x)) return(numeric(0))
  as.numeric(jsonlite::fromJSON(x))
}

.pg_text_array <- function(x) {
  inner <- paste0('"', gsub('"', '\\\\"', x), '"', collapse = ",")
  paste0("{", inner, "}")
}

.json_str_array <- function(x) {
  as.character(jsonlite::toJSON(as.character(x)))
}

.json_obj <- function(x) {
  if (!is.list(x) || !length(x)) return("{}")
  as.character(jsonlite::toJSON(x, auto_unbox = TRUE))
}

# Tolerant decoder for a family_codes / profile_codes cell coming from
# either backend: a JSON string (SQLite), a pg array literal "{a,b}", an
# already-parsed character vector (RPostgres array column), or NA.
.decode_any_array <- function(x) {
  if (is.null(x)) return(character(0))
  if (length(x) > 1L) return(as.character(x))
  if (is.list(x)) return(as.character(unlist(x)))
  if (is.na(x)) return(character(0))
  s <- as.character(x)
  if (!nzchar(s)) return(character(0))
  if (startsWith(s, "[")) {
    return(as.character(jsonlite::fromJSON(s)))
  }
  if (startsWith(s, "{") && endsWith(s, "}")) {
    inner <- substr(s, 2L, nchar(s) - 1L)
    if (!nzchar(inner)) return(character(0))
    parts <- strsplit(inner, ",", fixed = TRUE)[[1]]
    return(gsub('^"|"$', "", trimws(parts)))
  }
  s
}

.cosine_sim <- function(q, M) {
  if (is.null(dim(M))) M <- matrix(M, nrow = 1L)
  qn <- sqrt(sum(q^2))
  if (qn == 0) return(rep(0, nrow(M)))
  mn <- sqrt(rowSums(M^2))
  dots <- as.numeric(M %*% q)
  sim <- dots / (mn * qn)
  sim[!is.finite(sim)] <- 0
  sim
}


# ---- Source extraction -----------------------------------------------

.pdf_to_text <- function(path) {
  if (!requireNamespace("pdftools", quietly = TRUE)) {
    cli::cli_abort(c(
      "Package {.pkg pdftools} required to ingest PDF files.",
      "i" = "Install with {.code install.packages('pdftools')}."
    ))
  }
  pdftools::pdf_text(path)
}

# Turn a source argument into a list of segments (text + page number).
# PDFs become one segment per page; .txt/.md and raw text become a
# single segment with page = NA.
.source_to_segments <- function(source) {
  is_path <- is.character(source) && length(source) == 1L && !is.na(source)
  if (is_path && grepl("\\.pdf$", source, ignore.case = TRUE) && file.exists(source)) {
    pages <- .pdf_to_text(source)
    return(Map(function(t, p) list(text = t, page = p), pages, seq_along(pages)))
  }
  if (is_path && grepl("\\.(txt|md|markdown)$", source, ignore.case = TRUE) &&
      file.exists(source)) {
    txt <- paste(readLines(source, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
    return(list(list(text = txt, page = NA_integer_)))
  }
  txt <- paste(as.character(source), collapse = "\n")
  list(list(text = txt, page = NA_integer_))
}


# ---- Metadata validation ---------------------------------------------

.validate_doc_metadata <- function(metadata) {
  if (!is.list(metadata)) {
    cli::cli_abort("{.arg metadata} must be a named list.")
  }
  has_value <- function(k) {
    v <- metadata[[k]]
    !is.null(v) && length(v) == 1L && !is.na(v) && nzchar(as.character(v))
  }
  required <- c("title", "lang", "doc_type")
  miss <- required[!vapply(required, has_value, logical(1))]
  if (length(miss)) {
    cli::cli_abort("Missing required {.arg metadata} field{?s}: {.val {miss}}.")
  }
  valid_types <- c("paper", "report", "regulation", "manual", "note", "web")
  if (!metadata$doc_type %in% valid_types) {
    cli::cli_abort(c(
      "Invalid {.field doc_type}: {.val {metadata$doc_type}}.",
      "i" = "Must be one of {.val {valid_types}}."
    ))
  }
  pubd <- metadata$pub_date
  if (!is.null(pubd) && length(pubd) == 1L && !is.na(pubd)) {
    pubd <- tryCatch(
      as.Date(pubd),
      error = function(e) cli::cli_abort("{.field pub_date} not coercible to Date.")
    )
  } else {
    pubd <- NULL
  }
  clean_codes <- function(x) {
    if (is.null(x)) return(NULL)
    x <- as.character(x)
    x <- x[!is.na(x) & nzchar(x)]
    if (!length(x)) NULL else x
  }
  opt_chr <- function(k) if (!is.null(metadata[[k]])) as.character(metadata[[k]]) else NA_character_
  list(
    title         = as.character(metadata$title),
    author        = opt_chr("author"),
    publisher     = opt_chr("publisher"),
    pub_date      = pubd,
    lang          = as.character(metadata$lang),
    doc_type      = as.character(metadata$doc_type),
    source_url    = opt_chr("source_url"),
    license       = if (!is.null(metadata$license)) as.character(metadata$license) else "unknown",
    family_codes  = clean_codes(metadata$family_codes),
    profile_codes = clean_codes(metadata$profile_codes),
    extra         = if (is.list(metadata$extra)) metadata$extra else list(),
    ingested_by   = opt_chr("ingested_by")
  )
}


# ---- DB writers ------------------------------------------------------

.last_insert_id <- function(con) {
  if (.rag_is_pg(con)) {
    as.integer(DBI::dbGetQuery(con, "SELECT lastval() AS id")$id[1L])
  } else {
    as.integer(DBI::dbGetQuery(con, "SELECT last_insert_rowid() AS id")$id[1L])
  }
}

.rag_insert_document <- function(con, meta, embed_model) {
  is_pg <- .rag_is_pg(con)
  if (is_pg) {
    fam  <- if (length(meta$family_codes))  .pg_text_array(meta$family_codes)  else NA_character_
    prof <- if (length(meta$profile_codes)) .pg_text_array(meta$profile_codes) else NA_character_
  } else {
    fam  <- if (length(meta$family_codes))  .json_str_array(meta$family_codes)  else NA_character_
    prof <- if (length(meta$profile_codes)) .json_str_array(meta$profile_codes) else NA_character_
  }
  pubd <- if (is.null(meta$pub_date)) NA_character_ else as.character(meta$pub_date)
  params <- list(
    meta$title, meta$author, meta$publisher, pubd, meta$lang, meta$doc_type,
    meta$source_url, meta$license, fam, prof, embed_model,
    .json_obj(meta$extra), meta$ingested_by
  )
  if (is_pg) {
    sql <- paste0(
      "INSERT INTO knowledge_document ",
      "(title, author, publisher, pub_date, lang, doc_type, source_url, ",
      " license, family_codes, profile_codes, embed_model, metadata, ingested_by) ",
      "VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::text[], $10::text[], $11, ",
      " $12::jsonb, $13) RETURNING id"
    )
    return(as.integer(.db_get_query(con, sql, params = params)$id[1L]))
  }
  sql <- paste0(
    "INSERT INTO knowledge_document ",
    "(title, author, publisher, pub_date, lang, doc_type, source_url, ",
    " license, family_codes, profile_codes, embed_model, metadata, ingested_by) ",
    "VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)"
  )
  .db_execute(con, sql, params = params)
  .last_insert_id(con)
}

.rag_insert_chunk <- function(con, document_id, chunk_index, page_number,
                              text, text_hash, token_count, vec) {
  page_param <- if (is.null(page_number) || is.na(page_number)) {
    NA_integer_
  } else {
    as.integer(page_number)
  }
  if (.rag_is_pg(con)) {
    emb <- .pg_vector_literal(.fit_embedding_dim(vec, 3072L))
    sql <- paste0(
      "INSERT INTO knowledge_chunk ",
      "(document_id, chunk_index, page_number, text, text_hash, token_count, embedding) ",
      "VALUES ($1, $2, $3, $4, $5, $6, $7::vector) ",
      "ON CONFLICT (document_id, chunk_index) DO NOTHING"
    )
    .db_execute(con, sql, params = list(
      as.integer(document_id), as.integer(chunk_index), page_param,
      text, text_hash, as.integer(token_count), emb
    ))
  } else {
    sql <- paste0(
      "INSERT INTO knowledge_chunk ",
      "(document_id, chunk_index, page_number, text, text_hash, token_count, embedding) ",
      "VALUES ($1, $2, $3, $4, $5, $6, $7) ",
      "ON CONFLICT (document_id, chunk_index) DO NOTHING"
    )
    .db_execute(con, sql, params = list(
      as.integer(document_id), as.integer(chunk_index), page_param,
      text, text_hash, as.integer(token_count), .embedding_json(vec)
    ))
  }
}


#' Ingest a document into the RAG knowledge base
#'
#' Extracts text from a PDF / `.txt` / `.md` file (or a raw string),
#' splits it into overlapping chunks, embeds each chunk via the chosen
#' provider, and writes the document and its chunks to the knowledge
#' base. Runs in a single transaction so a failed embedding rolls back
#' cleanly.
#'
#' @param con A `DBIConnection`. RAG schema must be enabled
#'   ([enable_rag()]).
#' @param source Character. A path to a `.pdf` / `.txt` / `.md` file, or
#'   a raw text string (used directly when it is not an existing file
#'   path). PDFs are split one segment per page so chunks carry a
#'   `page_number`.
#' @param metadata Named list. Required: `title`, `lang` (ISO 639-1),
#'   `doc_type` (one of `paper`, `report`, `regulation`, `manual`,
#'   `note`, `web`). Optional: `author`, `publisher`, `pub_date`,
#'   `source_url`, `license` (default `"unknown"`), `family_codes`,
#'   `profile_codes`, `ingested_by`, and `extra` (a list stored as JSON
#'   `metadata`).
#' @param chunk_size,chunk_overlap Integer. Target chunk size and
#'   overlap, in estimated tokens. Defaults 512 / 50.
#' @param embed_provider One of `"mistral"` (default), `"openai"`,
#'   `"voyage"`.
#' @param api_key Character or `NULL`. Defaults to the provider's
#'   `NEMETON_<PROVIDER>_API_KEY` (or `<PROVIDER>_API_KEY`) environment
#'   variable.
#'
#' @return Invisibly, a list with `document_id`, `n_chunks`,
#'   `n_tokens_est`, `duration_sec`.
#'
#' @seealso [retrieve_knowledge()], [delete_knowledge_document()].
#' @export
ingest_knowledge_document <- function(con,
                                      source,
                                      metadata = list(),
                                      chunk_size = 512L,
                                      chunk_overlap = 50L,
                                      embed_provider = c("mistral", "openai", "voyage"),
                                      api_key = NULL) {
  .assert_rag_schema(con)
  embed_provider <- match.arg(embed_provider)
  t0 <- Sys.time()
  meta <- .validate_doc_metadata(metadata)

  segments <- .source_to_segments(source)
  chunks <- list()
  ci <- 0L
  for (seg in segments) {
    for (ct in .chunk_text(seg$text, chunk_size, chunk_overlap)) {
      chunks[[length(chunks) + 1L]] <- list(text = ct, page = seg$page,
                                             chunk_index = ci)
      ci <- ci + 1L
    }
  }
  if (!length(chunks)) {
    cli::cli_abort("No text could be extracted from {.arg source}.")
  }
  texts <- vapply(chunks, function(c) c$text, character(1))

  emb <- .embed_texts(texts, provider = embed_provider, api_key = api_key,
                      lang = meta$lang)
  if (is.null(dim(emb))) emb <- matrix(emb, nrow = 1L)
  if (nrow(emb) != length(texts)) {
    cli::cli_abort(
      "Embedding provider returned {nrow(emb)} vector{?s} for {length(texts)} chunk{?s}."
    )
  }
  embed_model <- paste0(embed_provider, ":", .provider_default_model(embed_provider))

  doc_id <- DBI::dbWithTransaction(con, {
    did <- .rag_insert_document(con, meta, embed_model)
    for (k in seq_along(chunks)) {
      ch <- chunks[[k]]
      .rag_insert_chunk(con, did, ch$chunk_index, ch$page, ch$text,
                        rlang::hash(ch$text), .estimate_tokens(ch$text),
                        emb[k, ])
    }
    did
  })

  invisible(list(
    document_id  = as.integer(doc_id),
    n_chunks     = length(chunks),
    n_tokens_est = sum(vapply(chunks, function(c) .estimate_tokens(c$text), integer(1))),
    duration_sec = as.numeric(difftime(Sys.time(), t0, units = "secs"))
  ))
}


#' Embed a query string into a numeric vector
#'
#' Thin wrapper over the configured embedding provider. Exported mainly
#' for debugging and batch indexing; [retrieve_knowledge()] calls it
#' internally.
#'
#' @param text Character scalar. The query to embed.
#' @param provider One of `"mistral"` (default), `"openai"`, `"voyage"`.
#' @param api_key Character or `NULL`. See [ingest_knowledge_document()].
#' @param lang Optional ISO 639-1 language hint (reserved for
#'   provider-specific model selection; currently unused).
#'
#' @return A numeric vector. Its length is provider-dependent (Mistral
#'   1024, OpenAI 1536/3072, Voyage 1024); it is fitted to 3072 dims
#'   only at storage/compare time.
#'
#' @export
embed_query <- function(text,
                        provider = c("mistral", "openai", "voyage"),
                        api_key = NULL,
                        lang = NULL) {
  provider <- match.arg(provider)
  if (!is.character(text) || length(text) != 1L || is.na(text) || !nzchar(text)) {
    cli::cli_abort("{.arg text} must be a non-empty character scalar.")
  }
  m <- .embed_texts(text, provider = provider, api_key = api_key, lang = lang)
  if (is.null(dim(m))) return(as.numeric(m))
  as.numeric(m[1L, ])
}


# ---- Retrieval -------------------------------------------------------

.empty_retrieval <- function() {
  data.frame(
    chunk_id    = integer(0),
    document_id = integer(0),
    title       = character(0),
    author      = character(0),
    pub_date    = as.Date(character(0)),
    source_url  = character(0),
    lang        = character(0),
    chunk_index = integer(0),
    page_number = integer(0),
    text        = character(0),
    similarity  = numeric(0),
    stringsAsFactors = FALSE
  )
}

.finalize_retrieval <- function(rows) {
  if (is.null(rows) || !nrow(rows)) return(.empty_retrieval())
  data.frame(
    chunk_id    = as.integer(rows$chunk_id),
    document_id = as.integer(rows$document_id),
    title       = as.character(rows$title),
    author      = as.character(rows$author),
    pub_date    = as.Date(rows$pub_date),
    source_url  = as.character(rows$source_url),
    lang        = as.character(rows$lang),
    chunk_index = as.integer(rows$chunk_index),
    page_number = as.integer(rows$page_number),
    text        = as.character(rows$text),
    similarity  = as.numeric(rows$similarity),
    stringsAsFactors = FALSE
  )
}

.warn_if_mixed_providers <- function(con) {
  models <- tryCatch(
    DBI::dbGetQuery(con,
      "SELECT DISTINCT embed_model FROM knowledge_document WHERE embed_model IS NOT NULL")$embed_model,
    error = function(e) character(0)
  )
  if (length(models) >= 2L) {
    cli::cli_warn(c(
      "The knowledge corpus mixes {length(models)} embedding models: {.val {models}}.",
      "i" = "Cosine similarity across providers is not meaningful.",
      "i" = "Re-embed the corpus with a single provider for reliable retrieval."
    ))
  }
}

.retrieve_pg <- function(con, qvec, top_k, family_codes, profile_codes,
                         min_similarity, lang) {
  qlit <- .pg_vector_literal(.fit_embedding_dim(qvec, 3072L))
  where <- character(0)
  if (!is.null(family_codes)) {
    where <- c(where, sprintf("d.family_codes && %s::text[]",
      DBI::dbQuoteLiteral(con, .pg_text_array(family_codes))))
  }
  if (!is.null(profile_codes)) {
    where <- c(where, sprintf("d.profile_codes && %s::text[]",
      DBI::dbQuoteLiteral(con, .pg_text_array(profile_codes))))
  }
  if (!is.null(lang)) {
    where <- c(where, sprintf("d.lang = %s", DBI::dbQuoteLiteral(con, lang)))
  }
  where_sql <- if (length(where)) paste("WHERE", paste(where, collapse = " AND ")) else ""
  sql <- sprintf(paste0(
    "SELECT c.id AS chunk_id, c.document_id AS document_id, d.title AS title, ",
    "d.author AS author, d.pub_date AS pub_date, d.source_url AS source_url, ",
    "d.lang AS lang, c.chunk_index AS chunk_index, c.page_number AS page_number, ",
    "c.text AS text, 1 - (c.embedding <=> '%s'::vector) AS similarity ",
    "FROM knowledge_chunk c JOIN knowledge_document d ON d.id = c.document_id ",
    "%s ORDER BY c.embedding <=> '%s'::vector LIMIT %d"
  ), qlit, where_sql, qlit, as.integer(top_k))
  rows <- DBI::dbGetQuery(con, sql)
  if (!nrow(rows)) return(.empty_retrieval())
  rows <- rows[!is.na(rows$similarity) & rows$similarity >= min_similarity, , drop = FALSE]
  .finalize_retrieval(rows)
}

.retrieve_sqlite <- function(con, qvec, top_k, family_codes, profile_codes,
                             min_similarity, lang) {
  rows <- DBI::dbGetQuery(con, paste0(
    "SELECT c.id AS chunk_id, c.document_id AS document_id, c.chunk_index AS chunk_index, ",
    "c.page_number AS page_number, c.text AS text, c.embedding AS embedding, ",
    "d.title AS title, d.author AS author, d.pub_date AS pub_date, ",
    "d.source_url AS source_url, d.lang AS lang, d.family_codes AS family_codes, ",
    "d.profile_codes AS profile_codes ",
    "FROM knowledge_chunk c JOIN knowledge_document d ON d.id = c.document_id"
  ))
  if (!nrow(rows)) return(.empty_retrieval())

  keep <- rep(TRUE, nrow(rows))
  if (!is.null(lang)) {
    keep <- keep & (rows$lang == lang)
  }
  if (!is.null(family_codes)) {
    keep <- keep & vapply(rows$family_codes, function(j) {
      length(intersect(.decode_any_array(j), family_codes)) > 0L
    }, logical(1))
  }
  if (!is.null(profile_codes)) {
    keep <- keep & vapply(rows$profile_codes, function(j) {
      length(intersect(.decode_any_array(j), profile_codes)) > 0L
    }, logical(1))
  }
  rows <- rows[keep, , drop = FALSE]
  if (!nrow(rows)) return(.empty_retrieval())

  d <- length(qvec)
  M <- t(vapply(rows$embedding, function(e) .fit_embedding_dim(.decode_embedding(e), d),
                numeric(d)))
  rows$similarity <- .cosine_sim(qvec, M)
  rows <- rows[order(-rows$similarity), , drop = FALSE]
  rows <- rows[rows$similarity >= min_similarity, , drop = FALSE]
  if (nrow(rows) > top_k) rows <- rows[seq_len(top_k), , drop = FALSE]
  .finalize_retrieval(rows)
}

#' Retrieve the most relevant knowledge chunks for a query
#'
#' Embeds `query` and returns the top-k chunks by cosine similarity,
#' optionally filtered by indicator family, actor profile, and language.
#' On PostgreSQL the ranking uses pgvector's `<=>` operator; on SQLite
#' it is computed in R.
#'
#' @param con A `DBIConnection`. RAG schema must be enabled.
#' @param query Character scalar. Natural-language query.
#' @param top_k Integer. Maximum number of chunks to return. Default 8.
#' @param family_codes Optional character vector. Keep only documents
#'   tagged with at least one of these family / indicator codes.
#' @param profile_codes Optional character vector. Keep only documents
#'   tagged with at least one of these actor-profile codes.
#' @param min_similarity Numeric in `[0, 1]`. Drop chunks below this
#'   cosine similarity. Default 0.7.
#' @param lang Optional ISO 639-1 code. Keep only documents in this
#'   language.
#' @param embed_provider One of `"mistral"` (default), `"openai"`,
#'   `"voyage"`. Must match the provider used at ingestion.
#'
#' @return A `data.frame` sorted by descending `similarity` with columns
#'   `chunk_id`, `document_id`, `title`, `author`, `pub_date`,
#'   `source_url`, `lang`, `chunk_index`, `page_number`, `text`,
#'   `similarity`. Zero rows (canonical empty frame) when nothing clears
#'   `min_similarity`.
#'
#' @seealso [format_citations()] to render the result as a citation
#'   block.
#' @export
retrieve_knowledge <- function(con,
                               query,
                               top_k = 8L,
                               family_codes = NULL,
                               profile_codes = NULL,
                               min_similarity = 0.7,
                               lang = NULL,
                               embed_provider = c("mistral", "openai", "voyage")) {
  .assert_rag_schema(con)
  embed_provider <- match.arg(embed_provider)
  if (!is.character(query) || length(query) != 1L || is.na(query) || !nzchar(query)) {
    cli::cli_abort("{.arg query} must be a non-empty character scalar.")
  }
  top_k <- as.integer(top_k)
  if (is.na(top_k) || top_k < 1L) {
    cli::cli_abort("{.arg top_k} must be a positive integer.")
  }
  if (!is.numeric(min_similarity) || length(min_similarity) != 1L ||
      is.na(min_similarity) || min_similarity < -1 || min_similarity > 1) {
    cli::cli_abort("{.arg min_similarity} must be a single number in [-1, 1].")
  }
  .warn_if_mixed_providers(con)
  qvec <- embed_query(query, provider = embed_provider)
  if (.rag_is_pg(con)) {
    .retrieve_pg(con, qvec, top_k, family_codes, profile_codes, min_similarity, lang)
  } else {
    .retrieve_sqlite(con, qvec, top_k, family_codes, profile_codes, min_similarity, lang)
  }
}


#' List the documents in the RAG knowledge base
#'
#' @param con A `DBIConnection`. RAG schema must be enabled.
#' @param lang,doc_type Optional filters (exact match).
#' @param family Optional single family / indicator code; keeps documents
#'   tagged with it.
#'
#' @return A `data.frame` of `knowledge_document` rows (without chunks),
#'   sorted by descending ingestion time. `family_codes` and
#'   `profile_codes` are returned as list-columns of character vectors.
#'
#' @export
list_knowledge_documents <- function(con, lang = NULL, doc_type = NULL,
                                     family = NULL) {
  .assert_rag_schema(con)
  rows <- DBI::dbGetQuery(con,
    "SELECT * FROM knowledge_document ORDER BY ingested_at DESC")
  if (!nrow(rows)) return(rows)
  if (!is.null(lang))     rows <- rows[rows$lang == lang, , drop = FALSE]
  if (!is.null(doc_type)) rows <- rows[rows$doc_type == doc_type, , drop = FALSE]
  if (nrow(rows)) {
    rows$family_codes  <- lapply(rows$family_codes,  .decode_any_array)
    rows$profile_codes <- lapply(rows$profile_codes, .decode_any_array)
  }
  if (!is.null(family) && nrow(rows)) {
    keep <- vapply(rows$family_codes, function(f) family %in% f, logical(1))
    rows <- rows[keep, , drop = FALSE]
  }
  rows
}


#' Delete a document and its chunks from the knowledge base
#'
#' @param con A `DBIConnection`. RAG schema must be enabled.
#' @param document_id Integer. `knowledge_document.id`.
#'
#' @return Invisibly, the number of chunks deleted (via the
#'   `ON DELETE CASCADE` foreign key).
#'
#' @export
delete_knowledge_document <- function(con, document_id) {
  .assert_rag_schema(con)
  if (length(document_id) != 1L || is.na(document_id) ||
      !is.finite(suppressWarnings(as.numeric(document_id)))) {
    cli::cli_abort("{.arg document_id} must be a single non-NA integer.")
  }
  did <- as.integer(document_id)
  n <- .db_get_query(con,
    "SELECT COUNT(*) AS n FROM knowledge_chunk WHERE document_id = $1",
    params = list(did))$n[1L]
  .db_execute(con, "DELETE FROM knowledge_document WHERE id = $1",
              params = list(did))
  invisible(as.integer(n))
}


#' Format retrieved chunks as a citation block
#'
#' Renders the result of [retrieve_knowledge()] as a numbered Markdown
#' (or HTML) "Sources" block, ready to concatenate to an AI perspective.
#' The footnote markers (`[^1]`, `[^2]`, ...) match the order of the rows.
#'
#' @param retrieved_chunks A `data.frame` returned by
#'   [retrieve_knowledge()].
#' @param format One of `"markdown"` (default) or `"html"`.
#' @param lang Language for the section heading. `"fr"` (default) ->
#'   "Sources documentaires"; anything else -> "Sources".
#'
#' @return A character scalar. Empty string `""` when there are no
#'   chunks.
#'
#' @export
format_citations <- function(retrieved_chunks,
                             format = c("markdown", "html"),
                             lang = "fr") {
  format <- match.arg(format)
  if (!is.data.frame(retrieved_chunks)) {
    cli::cli_abort("{.arg retrieved_chunks} must be a data.frame from {.fn retrieve_knowledge}.")
  }
  if (!nrow(retrieved_chunks)) return("")
  heading <- if (identical(lang, "fr")) "Sources documentaires" else "Sources"

  year_of <- function(d) {
    if (is.null(d) || is.na(d)) "" else format(as.Date(d), "%Y")
  }
  entries <- vector("list", nrow(retrieved_chunks))
  for (i in seq_len(nrow(retrieved_chunks))) {
    r <- retrieved_chunks[i, , drop = FALSE]
    author <- if (is.na(r$author)) "" else r$author
    yr <- year_of(r$pub_date)
    author_year <- if (nzchar(author) && nzchar(yr)) {
      sprintf("*%s, %s*", author, yr)
    } else if (nzchar(author)) {
      sprintf("*%s*", author)
    } else if (nzchar(yr)) {
      sprintf("*%s*", yr)
    } else {
      ""
    }
    pub_part <- "."
    page_part <- if (!is.na(r$page_number)) sprintf(" p. %d.", as.integer(r$page_number)) else ""
    title_part <- sprintf("\u00ab %s \u00bb", r$title)
    lead <- if (nzchar(author_year)) paste0(author_year, " \u2014 ") else ""
    entries[[i]] <- list(
      idx = i,
      text = sprintf("%s%s%s%s", lead, title_part, pub_part, page_part),
      url = if (!is.na(r$source_url) && nzchar(r$source_url)) r$source_url else NA_character_
    )
  }

  if (identical(format, "html")) {
    items <- vapply(entries, function(e) {
      body <- e$text
      if (!is.na(e$url)) {
        body <- sprintf('%s <a href="%s">[lien]</a>', body, e$url)
      }
      sprintf('  <li id="cite-%d">%s</li>', e$idx, body)
    }, character(1))
    return(sprintf("<h2>%s</h2>\n<ol>\n%s\n</ol>", heading,
                   paste(items, collapse = "\n")))
  }

  lines <- vapply(entries, function(e) {
    body <- e$text
    if (!is.na(e$url)) body <- sprintf("%s <%s>", body, e$url)
    sprintf("[^%d] %s", e$idx, body)
  }, character(1))
  sprintf("## %s\n\n%s", heading, paste(lines, collapse = "\n\n"))
}
