#' Site-index curves and estimation
#'
#' Reads the site-index reference CSV shipped with the package
#' and exposes helpers to estimate a stand site index from an
#' observed dominant height and age.
#'
#' These functions support the CHM-driven mode of
#' \code{\link{indicateur_p2_station}} (spec 005, phase 2). When a
#' Canopy Height Model is available, the CHM provides \eqn{H_{dom}},
#' the stand age is read from BD Forêt / inventory data, and
#' \code{compute_site_index()} returns the dominant height at a
#' reference age (by default 50 years), which is the classical
#' forestry definition of the site index.
#'
#' The curves are loaded once per R session from
#' \code{inst/extdata/site_index_curves.csv} and cached in an
#' internal environment.
#'
#' @name site_index
#' @keywords internal
NULL


# ============================================================
# Internal cache
# ============================================================

.site_index_cache <- new.env(parent = emptyenv())


#' Read the site-index reference curves
#'
#' Returns the full table of reference site-index curves shipped
#' with the package, with a per-session cache. The CSV is
#' generated by \code{data-raw/site_index_curves.R}.
#'
#' @return A \code{data.frame} with columns \code{species, age,
#'   class_1, ..., class_5}. Heights in metres.
#'
#' @examples
#' curves <- read_site_index_curves()
#' head(curves)
#'
#' @export
read_site_index_curves <- function() {
  if (!is.null(.site_index_cache$curves)) {
    return(.site_index_cache$curves)
  }

  path <- system.file("extdata", "site_index_curves.csv",
                      package = "nemeton")
  if (!nzchar(path) || !file.exists(path)) {
    stop("site_index_curves.csv not found in package extdata.",
         call. = FALSE)
  }

  curves <- utils::read.csv(path, stringsAsFactors = FALSE)

  required <- c("species", "age", paste0("class_", 1:5))
  missing <- setdiff(required, names(curves))
  if (length(missing) > 0) {
    stop("site_index_curves.csv is missing columns: ",
         paste(missing, collapse = ", "), call. = FALSE)
  }

  .site_index_cache$curves <- curves
  curves
}


# ============================================================
# Species lookup and fallback
# ============================================================

# Known conifer species codes in IFN style (used for fallback).
.conifer_codes <- c(
  "ABAL", "PIAB", "PISY", "PINI", "PIPI", "PIME",
  "PSME", "LADE", "CEAT", "CEDE", "JUCO"
)


#' Is a species code a conifer?
#'
#' Small helper used by the genus-level fallback logic in both
#' \code{\link{compute_site_index}} and
#' \code{\link{indicateur_p1_volume}}.
#'
#' @param species Character. Species code (IFN style).
#' @return Logical scalar. \code{TRUE} if the code is on the
#'   known conifer list.
#'
#' @keywords internal
is_conifer <- function(species) {
  if (is.na(species)) return(FALSE)
  toupper(species) %in% .conifer_codes
}


#' Resolve a species code to a row-group in the curves
#'
#' Given a raw species code, returns the code actually available
#' in the reference CSV. If the species is directly present,
#' returns it unchanged. Otherwise falls back to
#' \code{CONIFER_GENUS} or \code{BROADLEAF_GENUS} based on the
#' internal \code{.conifer_codes} list (used by
#' \code{\link{is_conifer}}).
#'
#' @param species Character. Species code (length 1).
#' @param available Character vector of species codes present in
#'   the curves.
#' @return Character scalar - the resolved species code, or
#'   \code{NA_character_} if neither the species nor its
#'   genus-level fallback is available.
#'
#' @keywords internal
resolve_species_code <- function(species, available) {
  if (is.na(species)) return(NA_character_)

  sp <- toupper(species)
  if (sp %in% available) return(sp)

  if (sp %in% .conifer_codes) {
    if ("CONIFER_GENUS" %in% available) return("CONIFER_GENUS")
  } else {
    if ("BROADLEAF_GENUS" %in% available) return("BROADLEAF_GENUS")
  }
  NA_character_
}


# ============================================================
# Public API
# ============================================================

#' List species covered by the site-index curves
#'
#' Returns the species codes available in
#' \code{inst/extdata/site_index_curves.csv}. Codes
#' \code{BROADLEAF_GENUS} and \code{CONIFER_GENUS} are
#' genus-level fallbacks automatically used when the input
#' species is not directly tabulated.
#'
#' @return A character vector of species codes.
#'
#' @examples
#' list_site_index_species()
#'
#' @export
list_site_index_species <- function() {
  curves <- read_site_index_curves()
  sort(unique(curves$species))
}


#' Published calibration points for the site-index curves
#'
#' Returns the set of per-species \eqn{(age, H_{class\_3})}
#' reference points against which the parameters in
#' \code{data-raw/site_index_curves.R} are tuned. Each row
#' carries the source citation so that downstream users can
#' audit the provenance of the curves, and the regression test
#' \code{test-site-index-calibration.R} asserts that the
#' generated CSV reproduces these points within a 0.5 m
#' tolerance (class_3 at the stated reference age).
#'
#' For Phase A species, the underlying equations differ (Duplat
#' & Tran-Ha 1997, Seynave 2005, Vallet & Pérot 2011…) but the
#' current Chapman-Richards approximation is calibrated to match
#' one published point per species. For FASY the full Korf model
#' from Bontemps et al. 2007 is used, so its calibration point
#' is the H(100) produced by the Bontemps parameters themselves.
#'
#' @return A data.frame with columns \code{species, age, h_class_3,
#'   source}.
#'
#' @examples
#' site_index_reference_points()
#'
#' @export
site_index_reference_points <- function() {
  data.frame(
    species   = c("QUPE", "QURO", "FASY", "CASA",
                  "PIAB", "ABAL", "PSME", "PISY",
                  "PIPI", "POSP"),
    age       = c(100L, 100L, 100L, 80L,
                  50L,  50L,  50L,  50L,
                  40L,  25L),
    h_class_3 = c(24.0, 22.0, 29.2, 22.0,
                  22.0, 20.0, 27.5, 16.5,
                  17.5, 23.5),
    source    = c("Duplat & Tran-Ha 1997",
                  "Duplat & Tran-Ha 1997",
                  "Bontemps et al. 2007 (Korf, NO+NE mean)",
                  "Dh\u00f4te-like scaling (IFN 2004)",
                  "Seynave et al. 2005",
                  "Vallet & P\u00e9rot 2011",
                  "DSF / IRSTEA 2010",
                  "Duplat 2001 follow-up",
                  "Lemoine 1991 (IFN Landes)",
                  "CNPF 2013 (peupleraie)"),
    stringsAsFactors = FALSE
  )
}


#' Estimate the site index from a dominant height and a stand age
#'
#' Given an observed dominant height \code{H_dom} (typically
#' derived from a Canopy Height Model) and the stand age, returns
#' the dominant height that the same fertility level would reach
#' at \code{reference_age}. This is the classical definition of
#' the site index in French forestry.
#'
#' The computation is a bilinear interpolation over the five
#' fertility classes tabulated in
#' \code{inst/extdata/site_index_curves.csv}:
#' \enumerate{
#'   \item At the observed \code{age}, find which pair of
#'         fertility classes brackets \code{H_dom}, and compute
#'         the fractional class \code{c} in \code{[1, 5]}.
#'   \item At \code{reference_age}, interpolate between the same
#'         pair of classes using \code{c}.
#' }
#'
#' When \code{species} is not directly tabulated, a genus-level
#' fallback is applied (\code{BROADLEAF_GENUS} for non-conifers,
#' \code{CONIFER_GENUS} otherwise).
#'
#' @param H_dom Numeric vector. Observed dominant height in
#'   metres.
#' @param age Numeric vector. Stand age in years.
#' @param species Character vector. Species codes (IFN style,
#'   4 letters). Recycled against \code{H_dom} / \code{age}.
#' @param reference_age Numeric scalar. Reference age at which
#'   the site index is returned (default 50).
#'
#' @return A numeric vector of the same length as the recycled
#'   inputs, giving the site index (dominant height at
#'   \code{reference_age}) in metres. \code{NA} is returned when
#'   \code{H_dom} or \code{age} is missing, when \code{age} is
#'   outside the tabulated range, or when the species cannot be
#'   resolved.
#'
#' @examples
#' # Sessile oak: 20 m at 80 years -> site index at 50 years
#' compute_site_index(H_dom = 20, age = 80, species = "QUPE")
#'
#' # Norway spruce: 25 m at 40 years
#' compute_site_index(H_dom = 25, age = 40, species = "PIAB")
#'
#' # Vectorised input
#' compute_site_index(
#'   H_dom   = c(20, 25, 18),
#'   age     = c(80, 40, 60),
#'   species = c("QUPE", "PIAB", "FASY")
#' )
#'
#' @export
compute_site_index <- function(H_dom,
                               age,
                               species,
                               reference_age = 50) {

  n <- max(length(H_dom), length(age), length(species))
  if (n == 0) return(numeric(0))

  H_dom   <- rep_len(H_dom, n)
  age     <- rep_len(age, n)
  species <- rep_len(as.character(species), n)

  if (!is.numeric(reference_age) || length(reference_age) != 1L ||
      is.na(reference_age) || reference_age <= 0) {
    stop("reference_age must be a positive scalar.", call. = FALSE)
  }

  curves    <- read_site_index_curves()
  available <- unique(curves$species)
  class_cols <- paste0("class_", 1:5)

  out <- numeric(n)

  for (i in seq_len(n)) {
    h_i <- H_dom[i]
    a_i <- age[i]
    s_i <- species[i]

    if (is.na(h_i) || is.na(a_i) || is.na(s_i) || h_i < 0 || a_i <= 0) {
      out[i] <- NA_real_
      next
    }

    sp_key <- resolve_species_code(s_i, available)
    if (is.na(sp_key)) {
      out[i] <- NA_real_
      next
    }

    sub <- curves[curves$species == sp_key, ]
    sub <- sub[order(sub$age), ]

    # Interpolate heights for each class at the observed age
    h_at_age <- vapply(class_cols, function(col) {
      stats::approx(x = sub$age, y = sub[[col]],
                    xout = a_i, rule = 1)$y
    }, numeric(1))

    if (anyNA(h_at_age)) {
      out[i] <- NA_real_
      next
    }

    # Heights at observed age are decreasing from class 1 to class 5
    # (best -> worst). Find which two classes bracket h_i.
    frac_class <- .frac_class(h_i, h_at_age)
    if (is.na(frac_class)) {
      out[i] <- NA_real_
      next
    }

    # Interpolate heights at reference_age per class
    h_at_ref <- vapply(class_cols, function(col) {
      stats::approx(x = sub$age, y = sub[[col]],
                    xout = reference_age, rule = 1)$y
    }, numeric(1))

    if (anyNA(h_at_ref)) {
      out[i] <- NA_real_
      next
    }

    # Linear interpolation between the bracketing classes at ref age
    lo <- floor(frac_class)
    hi <- min(lo + 1, 5L)
    if (lo < 1L) lo <- 1L
    w  <- frac_class - lo
    out[i] <- (1 - w) * h_at_ref[lo] + w * h_at_ref[hi]
  }

  out
}


# Helper: given an observed H and the 5 heights at a given age
# (ordered class 1 = tallest to class 5 = shortest), return a
# fractional class index in [1, 5]. Returns NA if H is outside
# the extrapolation range (clamped).
#
# @keywords internal
.frac_class <- function(h, h_classes) {
  # h_classes length 5, monotonically decreasing
  # Clamp to the tabulated range — out-of-range heights map to
  # the nearest class boundary.
  if (h >= h_classes[1]) return(1)
  if (h <= h_classes[5]) return(5)

  for (k in 1:4) {
    upper <- h_classes[k]     # tallest between k and k+1
    lower <- h_classes[k + 1] # shortest
    if (h <= upper && h >= lower) {
      if (upper == lower) return(k + 0.5)
      w <- (upper - h) / (upper - lower)
      return(k + w)
    }
  }
  NA_real_
}
