#' Tutorial datasets downloaded on demand (tutorials 07 and 08)
#'
#' @description
#' The LiDAR datasets used by the `07-lidar-advanced` (`aba.model`, ~97 MB)
#' and `08-coregistration` (`coregistration`, ~3.4 MB) tutorials are kept
#' in the git repository (`inst/extdata/aba.model/`,
#' `inst/extdata/coregistration/`) but excluded from the package build
#' (`.Rbuildignore`). An installed package therefore does not ship them:
#' `.tutorial_data_dir()` returns a local copy, downloading the missing
#' files once into the nemeton cache.
#'
#' **Source URL.** Files are fetched from the raw files of the GitHub
#' repository at the tag of the installed version:
#' `https://raw.githubusercontent.com/pobsteta/nemeton/v<X.Y.Z>/inst/extdata/<dataset>/<file>`.
#' A development version (`X.Y.Z.9000`, no tag) reads branch `main`. The
#' file list, sizes and MD5 sums come from
#' `inst/extdata/tutorial_data_manifest.csv` (regenerated by
#' `data-raw/tutorial_data_manifest.R`); every download is checked
#' against them.
#'
#' **Cache.** `file.path(get_global_cache_dir(), "tutorials", <ref>, <dataset>)`,
#' one folder per tag so versions never mix. Set `NEMETON_CACHE_DIR` to
#' move it.
#'
#' **Offline.** If a file cannot be downloaded, the call stops with an
#' explicit error naming the dataset, the URL and the manual way out
#' (copy `inst/extdata/<dataset>` from a clone of the repository into the
#' cache folder).
#'
#' In a source checkout (or under `devtools::load_all()`), the data are
#' found under `inst/extdata/` and nothing is downloaded.
#'
#' @name tutorial_data
#' @keywords internal
NULL

.TUTORIAL_DATASETS <- c("aba.model", "coregistration")
.TUTORIAL_DATA_REPO <- "pobsteta/nemeton"

# Référence git d'où tirer les fichiers : tag `vX.Y.Z` pour une version
# stable, branche `main` pour une version de développement (X.Y.Z.9000).
# Vaut aussi pour le schéma calendaire AAAA.M.N (spec 057 § 8) : le mois sans
# zéro en tête garantit que le tag reconstruit est identique à DESCRIPTION.
.tutorial_data_ref <- function(version = utils::packageVersion("nemeton")) {
  v <- unlist(unclass(package_version(as.character(version))))
  if (length(v) == 3L) paste0("v", paste(v, collapse = ".")) else "main"
}

.tutorial_data_url <- function(path, ref = .tutorial_data_ref()) {
  sprintf("https://raw.githubusercontent.com/%s/%s/inst/extdata/%s",
          .TUTORIAL_DATA_REPO, ref, path)
}

.tutorial_data_manifest <- function() {
  f <- system.file("extdata", "tutorial_data_manifest.csv", package = "nemeton")
  if (!nzchar(f)) {
    cli::cli_abort("Tutorial data manifest {.file tutorial_data_manifest.csv} not found in nemeton.")
  }
  utils::read.csv(f, stringsAsFactors = FALSE,
                  colClasses = c("character", "character", "numeric", "character"))
}

# Téléchargement d'un fichier (isolé pour être simulé dans les tests).
.tutorial_download <- function(url, destfile) {
  utils::download.file(url, destfile, mode = "wb", quiet = TRUE)
}

# Fichier présent et conforme au manifeste (taille + MD5).
.tutorial_file_ok <- function(file, size, md5) {
  file.exists(file) &&
    isTRUE(file.size(file) == size) &&
    identical(unname(tools::md5sum(file)), md5)
}

#' @rdname tutorial_data
#' @param dataset Character(1). `"aba.model"` (tutorial 07) or
#'   `"coregistration"` (tutorial 08).
#' @param cache_dir Character. Cache root. Defaults to
#'   [get_global_cache_dir()].
#' @param ref Character. Git reference (tag or branch). Defaults to the tag
#'   of the installed version (`main` for a development version).
#' @param use_local Logical. Use `inst/extdata/<dataset>` when the package
#'   provides it (source checkout). Default `TRUE`.
#' @param quiet Logical. Suppress progress messages. Default `FALSE`.
#' @return Character(1). Path of a local directory holding the dataset.
#' @keywords internal
.tutorial_data_dir <- function(dataset = c("aba.model", "coregistration"),
                               cache_dir = get_global_cache_dir(),
                               ref = .tutorial_data_ref(),
                               use_local = TRUE,
                               quiet = FALSE) {
  dataset <- match.arg(dataset)

  if (isTRUE(use_local)) {
    local <- system.file("extdata", dataset, package = "nemeton")
    if (nzchar(local) && dir.exists(local)) return(local)
  }

  man <- .tutorial_data_manifest()
  man <- man[man$dataset == dataset, , drop = FALSE]
  if (!nrow(man)) {
    cli::cli_abort("Dataset {.val {dataset}} is missing from the tutorial data manifest.")
  }

  root   <- file.path(cache_dir, "tutorials", ref)
  target <- file.path(root, dataset)
  # Chemins du manifeste relatifs à inst/extdata/ (préfixés par le dataset).
  dest <- file.path(root, man$path)
  ok <- mapply(.tutorial_file_ok, dest, man$size, man$md5)
  if (all(ok)) return(target)

  todo <- which(!ok)
  if (!quiet) {
    cli::cli_inform(c(
      "i" = "Downloading tutorial data {.val {dataset}} ({length(todo)} file{?s}, {format(structure(sum(man$size[todo]), class = 'object_size'), units = 'auto')}) into {.path {target}}.",
      " " = "Source: {.url https://github.com/{(.TUTORIAL_DATA_REPO)}/tree/{ref}/inst/extdata/{dataset}}"
    ))
  }

  for (i in todo) {
    url <- .tutorial_data_url(man$path[i], ref)
    dir.create(dirname(dest[i]), recursive = TRUE, showWarnings = FALSE)
    tmp <- paste0(dest[i], ".part")
    err <- tryCatch({
      suppressWarnings(.tutorial_download(url, tmp))
      NULL
    }, error = function(e) conditionMessage(e))
    if (is.null(err) && !.tutorial_file_ok(tmp, man$size[i], man$md5[i])) {
      err <- "downloaded file does not match the manifest (size or MD5)"
    }
    if (!is.null(err)) {
      unlink(tmp)
      cli::cli_abort(c(
        "Cannot download the tutorial data {.val {dataset}}.",
        "x" = "{.url {url}}: {err}",
        "i" = "These data are not shipped with the installed package; they are fetched once from GitHub. Check your network connection (are you offline?) and retry.",
        "i" = "Offline alternative: copy {.path inst/extdata/{dataset}} from a clone of {.url https://github.com/{(.TUTORIAL_DATA_REPO)}} (tag {.val {ref}}) into {.path {target}}."
      ), class = "nemeton_tutorial_data_offline")
    }
    file.rename(tmp, dest[i])
  }
  target
}
